#!/bin/sh
echo "*** starting dbus-ble-advertisements ***"
exec 2>&1
. /etc/profile.d/profile.sh

echo "Starting BLE advertisements service..."
cd /data/apps/dbus-ble-advertisements
exec softlimit -d 100000000 -s 1000000 -a 100000000 python3 -u dbus-ble-advertisements.py
